config/routes.rb
Rails.application.routes.draw do
  root 'qwwwotes#index'
  resources :qwwwotes
  resources :tags

end

app/models/qwwwote.rb
class Qwwwote < ActiveRecord::Base
  validates :quote, presence: true
  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :qwwwotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/qwwwotes_controller.rb
class QwwwotesController < ApplicationController

  def index
    @qwwwotes = Qwwwote.all
  end

  def show
    @qwwwote = Qwwwote.find(params[:id])
  end

  def new
    @qwwwote = Qwwwote.new
  end

  def edit
    @qwwwote = Qwwwote.find(params[:id])
  end

  def create
    @qwwwote = Qwwwote.new(qwwwote_params)
    if @qwwwote.save
      redirect_to @qwwwote
    else
      render 'new'
    end
  end

  def update
    @qwwwote = Qwwwote.find(params[:id])
    if @qwwwote.update(qwwwote_params)
      redirect_to @qwwwote
    else
      render 'edit'
    end
  end

  def destroy
    @qwwwote = Qwwwote.find(params[:id])
    @qwwwote.destroy

    redirect_to qwwwotes_path
  end

  private
    def qwwwote_params
      params.require(:qwwwote).permit(
      :quote,
      :author,
      :source,
      :source_url,
      :date,
      :tags,
      :notes)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qwwwotes_helper.rb
module QwwwotesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qwwwotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/qwwwotes/_form.html.erb
<%= form_for @qwwwote do |f| %>
  <% if @qwwwote.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@qwwwote.errors.count, 'error') %>
        prohibited this qwwwote from being saved:
      </h2>
      <ul>
        <% @qwwwote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :quote %><br>
    <%= f.text_area :quote %>
  </p>
  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </p>
  <p>
    <%= f.label :source_url %><br>
    <%= f.url_field :source_url %>
  </p>
  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </p>
  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/qwwwotes/edit.html.erb
<h1>You are editing now</h1>

<%= render 'form' %>

<%= link_to 'Back to the list of Qwwwotes', qwwwotes_path %>

app/views/qwwwotes/index.html.erb
<h1>Qwwotes</h1>
<p>Sage advice from web dev experts.</p>

<h1>Listing Qwwwotes</h1>

  <% @qwwwotes.each do |qwwwote| %>
    Quote: <%= qwwwote.quote %><br>

    Author: <%= qwwwote.author %><br>

    Source: <%= qwwwote.source %><br>

    URL: <%= qwwwote.source_url %><br>

    Date: <%= qwwwote.date %><br>

    Tags: <%= qwwwote.tags %><br>

    Notes: <%= qwwwote.notes %><br>

    <%= link_to 'Show this qwwwote', qwwwote_path(qwwwote) %>

    <%= link_to 'Edit this qwwwote', edit_qwwwote_path(qwwwote) %>

    <%= link_to 'Delete this qwwwote', qwwwote_path(qwwwote),
              method: :delete,
              data: { confirm: 'Noooooooooooooooooos. Unless you really want to:' } %>

    <hr>
  <% end %>
<%= link_to 'Add a qwwwote!', new_qwwwote_path %>

app/views/qwwwotes/new.html.erb
<h1>You are submitting a qwwwote</h1>

<%= render 'form' %>

<%= link_to 'Back to the list of Qwwwotes', qwwwotes_path %>

app/views/qwwwotes/show.html.erb
<h1>A Qwwwote</h1>

Quote: <%= @qwwwote.quote %><br>
Author: <%= @qwwwote.author %><br>
Source: <%= @qwwwote.source %><br>
URL: <%= @qwwwote.source_url %><br>
Date: <%= @qwwwote.date %><br>
Tages: <%= @qwwwote.tags %><br>
Notes: <%= @qwwwote.notes %><br><br>

<h2>Add a tag:</h2>
<%= form_for([@qwwwote, @qwwwote.tags.build]) do |f| %>

  <p>
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit this qwwwote', edit_qwwwote_path(@qwwwote) %><br><br>

<%= link_to 'Back to the list of Qwwwotes', qwwwotes_path %>